### ISSUE TITLE
Visualization of predictions

### ISSUE THREAD

**Issue by jollesti** [xupei0610/SocialVAE#1]
Hi! 
Is it possible to get out the predicted coordinates (txt file or similar)? My intention would be to visualize the predictions. Or would you recommend another way to do the visualization?

Thanks in advance!

**Comment by xupei0610** [comment]
You can easily collect the predictions after a simple forward call of the SocialVAE model. See https://github.com/xupei0610/SocialVAE/blob/71f190367f261c070ffeeb427aa9174197cb24f8/main.py#L172-L186 where `y_` is the predicted coordinates in the shape of `N_PREDICTIONS x PRED_HORIZON x N x 2`.
Or you can get the most-likely prediction result by passing the argument `n_predictions=0`.
