### ISSUE TITLE
NBA datasets visualization.

### ISSUE THREAD

**Issue by zhangkun07** [xupei0610/SocialVAE#11]
I really appreciate your work, it's an extremely wonderful job. But in the previous question, I didn't find a way to visualize the trajectory, regarding the NBA dataset. In one of the github nba dataset fetch addresses you provided, there is no image found of it to complete the data visualization. So please, do you have any more methods for NBA data visualization, looking forward to your reply!

**Comment by xupei0610** [comment]
This repo (https://github.com/linouk23/NBA-Player-Movements) provides an example of how to visualize SportVU data.
To draw a trajectory, just call plot function from matplotlib during visualization.
