### ISSUE TITLE
valid dataset

### ISSUE THREAD

**Issue by wangbei16** [xupei0610/SocialVAE#13]
I noticed that your code does not include a validation dataset, and the functionality of the validation dataset is being implemented by the test dataset. I want to know why.

**Comment by wangbei16** [comment]
cross-validation

**Comment by fses91** [comment]
Hi,

I want to comment on that, in the paper you write "We use the same preprocessing and evaluation methods as in prior works [17,2] and apply leaveone-out cross-validation.", but I don't see it implemented here.

I assume the results you report are not cross-validated, but just the best ckpt on the test set is reported?

Best regards,
