### ISSUE TITLE
Dataset preprocessing script

### ISSUE THREAD

**Issue by gnillling** [xupei0610/SocialVAE#14]
I really appreciate your work on SocialVAE. Could you share the code for preprocessing the dataset? I noticed that the UCY dataset provides pixel coordinates; how can these be converted into world coordinates?

**Comment by xupei0610** [comment]
The UCY dataset provides homography matrix through which it can be converted between the world coordinate and the pixel space. More details can be found at https://github.com/crowdbotp/OpenTraj/tree/master/datasets/UCY
