### ISSUE TITLE
How to train SocialVAE on SDD?

### ISSUE THREAD

**Issue by godnuan** [xupei0610/SocialVAE#4]
Hello, how to train the model on the SDD dataset? After I train the model with the config/sdd.py or config/sddpixel.py file, the test results of the model are very strange. The ADE in the result is more than 400.

**Comment by xupei0610** [comment]
Thanks for your feedback. 

I uploaded the wrong version of SDD training data. It should be the one defined in meters, which is consistent with the test data. But, the previous one is defined in pixels. I just fixed this issue. 

Thanks.
