### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by lvkaiboy** [xupei0610/SocialVAE#5]
Hello! 
    Thank you very much for the code you provided, I would like to study on the basis of your research. Can you provide visual code for my reference? Thank you very much！

**Comment by xupei0610** [comment]
Sorry for the late reply.

For drawing trajectories, it can be done easily using package like matploblib. Just using the frame extracted from the dataset video as the background of the plot. The homography can be estimated based on our data and the original data recorded in pixel. For example, you can find the annotation for Zara02 from https://github.com/crowdbotp/OpenTraj/blob/master/datasets/UCY/zara02/annotation.vsp and also the original video from the repository.

Below is the code we used to estimate the homography for Zara02:

      import numpy as np
      import cv2
      # zara02
      pts_img = np.array([[279, -123], [274, -102], [206, -102],[202, -72]])
      pts_img = np.stack((288-pts_img[:, 1], 360+pts_img[:, 0]), axis=-1)
      pts_wrd = np.array([[13.4487205051, 3.93788669527], [13.3434879503, 4.43907227467], [11.9123252048, 4.43907227467],[11.828139161,5.15505167381]])
      H, _ = cv2.findHomography(pts_img, pts_world)
      H_inv = np.linalg.inv(H)

For other datasets:

      # zara01
      pts_img = np.array([[311, -45], [182, -31], [-348, 129],[-258, 36]])
      pts_img = np.stack((288-pts_img[:, 1], 360+pts_img[:, 0]), axis=-1)
      pts_world = np.array([[14.1222088559, 5.79943313304], [11.4072089417, 6.13355685264], [0.252558131551, 9.95211364805],[2.14674411818, 7.73257751072]])

      # students003
      pts_img = np.array([[70, -35], [179, 22], [-71, -137],[-252, -28]])
      pts_img = np.stack((288-pts_img[:, 1], 360+pts_img[:, 0]), axis=-1)
      pts_world = np.array([[9.0499997139, 6.03809293275], [11.3440694088, 7.39845379112], [6.08244166818, 3.60376297567],[2.27302318396, 6.20515479255]])

The pixel coordinate of a given coordinate from our provided data recorded in meters can be obtained by

      p = H_inv @ [x, y, 1]
      row = p[..., 1]/p[..., 2]
      col = p[..., 0]/p[..., 2]


To draw a heatmap, just plot all the trajectories each of which as an image and stack all images together as the heatmap. We also apply a Gaussian blur to make the generated heatmap look smooth.

**Comment by lvkaiboy** [comment]
Thank you very much for your help.
