### ISSUE TITLE
Reproduced result on ETH dataset

### ISSUE THREAD

**Issue by sungjuune** [xupei0610/SocialVAE#6]
Hello, first of all, thank you for your motivational work!

I ran the provided script to newly train the datasets for sanity check, where I found that the result of ETH dataset is different from the reported result in the paper. HOTEL seems fine. I used the default config file. Is there a reason? Thanks.

![스크린샷, 2023-02-19 12-42-23](https://user-images.githubusercontent.com/103199477/219915732-30bd6cbb-b189-404e-af07-5b59d5f809c4.png)
![스크린샷, 2023-02-19 12-41-59](https://user-images.githubusercontent.com/103199477/219915754-1c078a60-252b-43a6-ba0a-8b7f96e7c2c1.png)

**Comment by xupei0610** [comment]
I just double checked. There should be no problem to reproduce the result on ETH dataset.

All my training and testing was run on V100 GPU with Pytorch 1.11 and CUDA 11.3.

**Comment by while-lin** [comment]
I cannot reproduce the results of eth dataset too．
