### ISSUE TITLE
NBA dataset

### ISSUE THREAD

**Issue by YonghaoDong** [xupei0610/SocialVAE#7]
您好，请问可以提供关于NBA数据集的更多信息吗（比如官方网址，或者包含视频以及场景图片的数据）。
我看有很多关于NBA的数据集，但是没有找到作者这个版本的

**Comment by xupei0610** [comment]
The following is what I know. Years ago, NBA employed SportVU to track and record the movement of players and the ball on the court, and provided the logs on the NBA stats website. But, those logs had been taken down from the official website. The current version of SportVU NBA movement data that can be found online is the recordings for 2015-16 season, which is originally posted on the [github](https://github.com/neilmj/BasketballData/tree/master/2016.NBA.Raw.SportVU.Game.Logs).
