### ISSUE TITLE
How to train SocialVAE with more features in data?

### ISSUE THREAD

**Issue by QihongKyronXue** [xupei0610/SocialVAE#8]
Hello! 
Thanks for your sharing of the project SocialVAE. I'm a new to learn something about pedestrian trajectory prediction. I have a question I want to ask for help. 
SocialVAE do the training and testing with the data form "frame id x y", this only consider the coordinates or position features and something computing from the position. But if I want to add more features, the data form will be more columns. For an instance, if I add sex(man or woman, represented by 1 and 0 respectively) as another feature to the data, the data can be listed as "frame id x y sex"，then     how to train the model, which parts should I modify in the codes. Aftering adding more features, then which parts should be modified correspondingly to make the model operate successfully. That's my question. Thanks for your patient reading and understanding!

**Comment by xupei0610** [comment]
You need to modify the dataloader function to support data files with more features.
See https://github.com/xupei0610/SocialVAE/blob/27e4a02375a655fe5a85c239bafeea57a4724d36/data.py#L299-L312
Change also https://github.com/xupei0610/SocialVAE/blob/27e4a02375a655fe5a85c239bafeea57a4724d36/data.py#L210-L227
to include more features in the generated training/testing data.

To introduce more features during model inference, please check https://github.com/xupei0610/SocialVAE/blob/27e4a02375a655fe5a85c239bafeea57a4724d36/social_vae.py#L194-L198

**Comment by QihongKyronXue** [comment]
Thanks a lot. It's helpful for me.
