### ISSUE TITLE
Could you please show me how to draw the neural network structure?

### ISSUE THREAD

**Issue by lgy250** [xupei0610/SocialVAE#9]
Thank you very much for sharing the work with us.
But when reading the code,I was confused about the net structure.So I drew one on the netron webset.(https://netron.app/)

Maybe I used the wrong trick,I got a net without connection as below.
If you could help me, it would be a great honor for me.
Thanks.
![kaiti_test pt](https://github.com/xupei0610/SocialVAE/assets/87751834/7a943fdc-a9b8-4e5c-b6b9-b2fcff82bec1)

**Comment by xupei0610** [comment]
We have a more detailed diagram in our previous version of the paper. Please refer to https://arxiv.org/abs/2203.08207v2.
Hope that could help you.

**Comment by xupei0610** [comment]
![‎overview ‎001](https://github.com/xupei0610/SocialVAE/assets/876313/eff0608d-f281-4d45-8ff0-ace1e411faa6)
There is a very verbose version of the system overview diagram.

**Comment by lgy250** [comment]
Thanks very much,it's very helpful.
